### ISSUE TITLE
add --mirror as an argument when cloning a repo

### ISSUE THREAD

**Issue by prayforbirdies** [gladwinbobby/bitbucket-repository-downloader#4]
First thank you. This is a giant help for me. I am planning to use it to backup all my repos as we are no longer using them but need to store them for compliance. 

Is it possible to add the ability to pass --mirror to the git args so we can download a full copy ? I have a ton of repos and that would be a big help and Im sure to others as well.  

Again THANKS!

**Comment by gladwinbobby** [comment]
Hi, thanks for trying this project. I'll look into adding the --mirror tag soon.

**Comment by gladwinbobby** [comment]
Added --mirror option.
