### ISSUE TITLE
ability to skip a repo (by slug name perhaps) when downloading repos

### ISSUE THREAD

**Issue by prayforbirdies** [gladwinbobby/bitbucket-repository-downloader#5]
Hi again,

Anyway to add the ability to skip a repo? I have a few hg repos in there and that breaks it.

Thanks!

**Comment by gladwinbobby** [comment]
Sure, will add an option to skip repos.

**Comment by prayforbirdies** [comment]
> Sure, will add an option to skip repos.

Thanks!

**Comment by gladwinbobby** [comment]
Added option to skip repos.

**Comment by prayforbirdies** [comment]
works like a charm! Thanks
