### ISSUE TITLE
Is too long

### ISSUE THREAD

**Issue by SalmaCzSz** [gladwinbobby/bitbucket-repository-downloader#7]
Hola, al tratar de descargar mis repositorios de Bitbucket recibo lo siguiente con 4 repositorios

```
[Error: failed to stat '<directorio>/<repo>': The filename or extension is too long.
] {
  errno: -4,
  errorFunction: 'Clone.clone'
}
```
¿Cómo podría solucionarlo?
Gracias.

**Comment by gladwinbobby** [comment]
Maybe you're trying to clone the repositories in a nested directory with a very long filename. Can you run the script from a top level directory?

**Comment by SalmaCzSz** [comment]
Thanks a million. 😄
