### ISSUE TITLE
Clone all branches

### ISSUE THREAD

**Issue by archerne** [gladwinbobby/bitbucket-repository-downloader#9]
Would it be possible to add a flag that would also download all branches of repositories? In looking at a way to backup all of my code I am realizing that not everything is in the 'master' branches and it would be nice to have all branches available.

**Comment by gladwinbobby** [comment]
I hope what you're looking for is the --mirror argument. It clones the entire repository with all the branches.

**Comment by archerne** [comment]
I must be missing something then. When I run with the --mirror flag I don't get any of the files from the repo and a significantly smaller clone. The repo that I am trying it on has 3 branches, but with the mirror flag the branches folder is empty as is the refs folder (it has a heads and a tags folder but nothing in either). Am i missing something to see/get all of the code for each of the branches?
